# Generated by Django 5.1 on 2024-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "invite_code",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("invite_used", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
