# Generated by Django 5.1 on 2024-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(max_length=4),
        ),
    ]
