# Generated by Django 5.1 on 2024-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_app", "0002_alter_userprofile_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
