# Generated by Django 5.1 on 2024-09-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral_app", "0003_alter_userprofile_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
