# Generated by Django 5.1 on 2024-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_app", "0004_alter_userprofile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
