# Generated by Django 5.1 on 2024-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "referral_app",
            "0006_alter_userprofile_managers_userprofile_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="auth_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
