# Generated by Django 5.1.1 on 2024-09-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_shop', '0002_alter_networknode_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='level',
        ),
    ]
