# Generated by Django 5.1.1 on 2024-09-24 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_shop', '0003_remove_networknode_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknode',
            options={'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
        migrations.AlterField(
            model_name='networknode',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email'),
        ),
    ]
