# Generated by Django 5.1.1 on 2024-09-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_shop', '0004_alter_networknode_options_alter_networknode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
